# Generated by Django 5.0.4 on 2024-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
